### ISSUE TITLE
Latest version creates conflicts with peers

### ISSUE THREAD

**Issue by gbbr** [sindresorhus/grunt-eslint#132]
Hi @sindresorhus 

Feel free to close this issue if you find it is unrelated to the project. I am using [`dgeni-packages`](https://github.com/angular/dgeni-packages) (via [`dgeni-alive`](https://github.com/wingedfox/dgeni-alive)) in my project and it fails to work with `grunt-eslint@19.0.0`, but works fine with `grunt-eslint@^16.0.0`. This is a really odd issue that has been causing me quite some problems. It definitely has something to do with some peer dependencies as far as I can suspect.

The error I get from dgeni is:
```
info:    running processor: extractJSDocCommentsProcessor
error:   Error: Unknown node type JSXElement.
    at Controller.traverse (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/estraverse/estraverse.js:521:31)
    at traverse (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/estraverse/estraverse.js:713:27)
    at findNodeAfter (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/dgeni-packages/jsdoc/processors/extractJSDocComments.js:82:3)
    at /Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/dgeni-packages/jsdoc/processors/extractJSDocComments.js:57:32
    at arrayEach (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/lodash/lodash.js:9344:14)
    at /Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/dgeni-packages/jsdoc/processors/extractJSDocComments.js:47:11
    at arrayFilter (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/lodash/lodash.js:603:11)
    at Function.filter (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/lodash/lodash.js:9175:14)
    at Object.$process (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/dgeni-packages/jsdoc/processors/extractJSDocComments.js:40:16)
    at /Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/dgeni/lib/Dgeni.js:202:28
    at _fulfilled (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/q/q.js:796:13)
    at /Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/q/q.js:857:14
    at runSingle (/Users/Gabriel/go/src/github.com/superdesk/superdesk-client-core/node_modules/q/q.js:137:13)
```
It might be related to `espree` or `eslint`. Any ideas?

**Comment by sindresorhus** [comment]
No idea. Sorry. Try the ESLint support channels.

**Comment by gbbr** [comment]
Oh i've fixed this ages ago and forgot to close it. The prepackaged dgeni version I was using, called dgeni-alive, was missing 'estraverse-fb', which it now has. 

I'm gonna leave this here in case it helps someone else in the future.
