### ISSUE TITLE
Different output between `eslint` and `grunt eslint`

### ISSUE THREAD

**Issue by pdehaan** [sindresorhus/grunt-eslint#69]
I have an invalid .eslintrc rule, apparently, which I found out by running `$ eslint .` on the command line:
```
$ eslint --version # v0.23.0
$ eslint .

/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config-validator.js:88
        throw new Error(message.join(""));
              ^
Error: /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/.eslintrc:
	Configuration for rule "no-use-before-define" is invalid:
	Value "true" is the wrong type.

    at validateRuleOptions (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config-validator.js:88:15)
    at /Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config-validator.js:101:13
    at Array.forEach (native)
    at Object.validate (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config-validator.js:100:35)
    at loadConfig (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:99:19)
    at getLocalConfig (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:225:23)
    at Config.getConfig (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/config.js:363:22)
    at processText (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/cli-engine.js:183:27)
    at processFile (/Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/pdehaan/.npm-packages/lib/node_modules/eslint/lib/cli-engine.js:322:26
```

Where my .eslintrc file has the following:
```
$ cat .eslintrc
{
  "env": {
    "amd": true,
    "es6": true,
    "mocha": true,
    "node": true
  },
  "rules": {
    ...
    "no-use-before-define": true,
    "no-with": 2,
    ...
  }
}
```

**NOTE:** `eslint` is complaining about that `"no-use-before-define": true` rule, since that `true` should be a `0`, `1`, or `2`.

BUT, this gets interesting when I run `grunt eslint`, which tells me everything is fine.

```
$ cat package.json | grep "eslint"
    "grunt-eslint": "14.0.0",
$ ./node_modules/grunt-eslint/node_modules/.bin/eslint --version
v0.22.1

$ grunt eslint
Running "eslint:grunt" (eslint) task


Running "eslint:app" (eslint) task


Running "eslint:tests" (eslint) task


Running "eslint:scripts" (eslint) task


Running "eslint:server" (eslint) task


Done, without errors.


Execution Time (2015-06-16 18:03:21 UTC)
loading tasks   2.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 22%
eslint:grunt   481ms  ▇▇▇▇▇ 5%
eslint:app        6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 60%
eslint:tests      1s  ▇▇▇▇▇▇▇▇▇▇ 10%
eslint:server  325ms  ▇▇▇▇ 3%
Total 10.1s
```

Not sure why `$ eslint .` fails hard on invalid .eslintrc rules, but `grunt eslint` replies with "Done, without errors."

**Comment by pdehaan** [comment]
Ugh, sorry, I should have figured it out from my version checks... If I update to the latest **grunt-eslint** which uses the latest **eslint**, then everything blows up spectacularly, as expected.

```
$ npm ls | grep eslint
├─┬ grunt-eslint@15.0.0
│ └─┬ eslint@0.23.0

$ ./node_modules/grunt-eslint/node_modules/.bin/eslint --version
v0.23.0

$ grunt eslint
Running "eslint:grunt" (eslint) task
Warning: /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/.eslintrc:
	Configuration for rule "no-use-before-define" is invalid:
	Value "true" is the wrong type.
 Use --force to continue.

Aborted due to warnings.
```
